#!/usr/bin/env node

import chalk from "chalk"
import chalkAnimation from 'chalk-animation';
import inquier from "inquirer"
import randomWords from "random-words"
import figlet from "figlet"
import gradient from "gradient-string"

let word
let amoutOfWords = 15
let board = ""
let timer = 60
let attempts = 3
let rightWords = 0

const sleep = (ms = 2000) => new Promise((r) => setTimeout(r, ms))

async function welcome() {
	console.clear()
	const title = chalkAnimation.radar("Fast as fucc boiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii", 5, 1)
	await sleep(1000)
	title.stop()
	console.clear()

	console.log(`Welcome to ${chalk.bgWhite(chalk.black(chalk.bold(" FaFb ")))}
by ${chalk.bgBlue("Nick :)")}

${chalk.bold("HoW tO PlAY? ")}

	${chalk.red("uKindaCute")} -> ${chalk.green("uKindaCute")}

Attempts left: x    Time left: (only updates when u insert a word)
? > uKindaCute
	`)

	const options = await inquier.prompt({
		name: 'difficulty',
		type: 'list',
		message: 'Choose the difficulty\n',
		choices: [
			'Easy',
			'Medium',
			'Hard',
			'Yes'
		],
	})

	await gameSetup(options)

	console.clear()
	console.log(figlet.textSync("3", { font: 'letters' }));
	await sleep(750)
	console.clear()
	console.log(figlet.textSync("2", { font: 'letters' }));
	await sleep(750)
	console.clear()
	console.log(figlet.textSync("1", { font: 'letters' }));
	await sleep(750)

}

async function gameSetup(options) {

	board = ""
	rightWords = 0
	switch (options.difficulty) {
		case 'Easy':
			timer = 60
			attempts = 3
			amoutOfWords = 15
			break;
		case 'Medium':
			timer = 45
			attempts = 2
			amoutOfWords = 20
			break;
		case 'Hard':
			timer = 30
			attempts = 1
			amoutOfWords = 20
		case 'Yes':
			timer = 20
			attempts = 1
			amoutOfWords = 30
		default:
			break;
	}

}

async function boardGenerator() {
	let dictionary = randomWords(amoutOfWords)
	let spacesInLine

	dictionary.map((randomWord) => {
		spacesInLine = Math.round(50 - (Math.random() * 50))
		board += " ".repeat(spacesInLine) + chalk.red(randomWord) + '\n'
	})

}

function startTime() {
	timer--
}

async function startGame() {
	setInterval(startTime, 1000);
	while (attempts > 0 && rightWords < amoutOfWords && timer > 0) {
		console.clear()
		console.log(board)
		await getWord()
		await verifyWord()
	}
	clearInterval(startTime)
}

async function getWord() {
	const answer = await inquier.prompt({
		name: "word",
		type: "input",
		message: "Attempts: " + attempts + "      Time left: " + timer + "\n>"
	})
	word = answer.word
}

async function verifyWord() {

	if (board.indexOf(chalk.red(word)) != -1) {
		board = board.replace(chalk.red(word), chalk.green(word))
		rightWords++
	}
	else
		attempts--
}

function loser() {
	console.clear()
	console.log(`${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}${chalk.bgRed(chalk.black("Loser!"))}
	`)
	process.exit(1)
}

async function winner() {
	console.clear()
	const winner = await `Winner!!!!!!!!!!!`
	await figlet(winner, (err, data) => {
		console.log(gradient.pastel.multiline(data))
	})
	await sleep(50)
	const again = await inquier.prompt({
		name: 'answer',
		message: 'Play again? ',
		type: 'confirm'
	})

	if (again.answer)
		await game()
	process.exit(1)
}

async function game() {
	await welcome()
	await boardGenerator()
	await startGame()
	if (rightWords == amoutOfWords)
		await winner()
	else
		await loser()
}

await game()




